Garage/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin

from views import car_views, \
    insurance_views, \
    carissue_views, \
    improvement_views, \
    repair_views, \
    views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.main_view, name='main'),
    path('about/', views.about, name='about'),
    path('contacts/', views.contacts, name='contacts'),

    path('cars/', car_views.get_cars, name='cars'),
    path('cars/archived/', car_views.get_archived_cars, name='archived_cars'),
    path('car/<int:car_id>', car_views.get_car, name='car_profile'),
    path('car/add/', car_views.add_car, name='add_car'),
    path('car/update/<int:car_id>', car_views.update_car, name='update_car'),
    path('car/delete/<int:car_id>', car_views.delete_car, name='delete_car'),
    path('car/archive/<int:car_id>', car_views.archive_car, name='archive_car'),
    path('car/unarchive/<int:car_id>', car_views.unarchive_car, name='unarchive_car'),
    path('car/<int:car_id>/upload_image/', views.upload_photo, name='upload_image'),

    path('insurances/', insurance_views.get_insurances, name='insurances'),
    path('insurances/archived/', insurance_views.get_archived_insurances, name='archived_insurances'),
    path('insurance/add/', insurance_views.add_insurance, name='add_insurance'),
    path('insurance/update/<int:insrnc_id>', insurance_views.update_insurance, name='update_insurance'),
    path('insurance/delete/<int:insrnc_id>', insurance_views.delete_insurance, name='delete_insurance'),
    path('insurance/archive/<int:insrnc_id>', insurance_views.archive_insurance, name='archive_insurance'),
    path('insurance/unarchive/<int:insrnc_id>', insurance_views.unarchive_insurance, name='unarchive_insurance'),

    path('issues/', carissue_views.get_carissues, name='car_issues'),
    path('issues/archived/', carissue_views.get_archived_issues, name='archived_issues'),
    path('issue/add/', carissue_views.add_issue, name='add_issue'),
    path('issue/update/<int:issue_id>', carissue_views.update_issue, name='update_issue'),
    path('issue/delete/<int:issue_id>', carissue_views.delete_issue, name='delete_issue'),
    path('issue/archive/<int:issue_id>', carissue_views.archive_issue, name='archive_issue'),
    path('issue/unarchive/<int:issue_id>', carissue_views.unarchive_issue, name='unarchive_issue'),

    path('improvements/', improvement_views.get_improvements, name='improvements'),
    path('improvements/archived/', improvement_views.get_archived_improvements, name='archived_improvements'),
    path('improvement/add/', improvement_views.add_improvement, name='add_improvement'),
    path('improvement/update/<int:impr_id>', improvement_views.update_improvement, name='update_improvement'),
    path('improvement/delete/<int:impr_id>', improvement_views.delete_improvement, name='delete_improvement'),
    path('improvement/archive/<int:impr_id>', improvement_views.archive_improvement, name='archive_improvement'),
    path('improvement/unarchive/<int:impr_id>', improvement_views.unarchive_improvement, name='unarchive_improvement'),

    path('repairs/', repair_views.get_repairs, name='repairs'),
    path('repairs/archived/', repair_views.get_archived_repairs, name='archived_repairs'),
    path('repair/add/', repair_views.add_repair, name='add_repair'),
    path('repair/update/<int:repair_id>', repair_views.update_repair, name='update_repair'),
    path('repair/delete/<int:repair_id>', repair_views.delete_repair, name='delete_repair'),
    path('repair/archive/<int:repair_id>', repair_views.archive_repair, name='archive_repair'),
    path('repair/unarchive/<int:repair_id>', repair_views.unarchive_repair, name='unarchive_repair'),

    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_ROOT, document_root=settings.MEDIA_ROOT)

Garage/models.py
import datetime
import os
from django.core.validators import MinValueValidator, MaxValueValidator

from django.db import models
from django.contrib.auth.models import User

from Garage import settings

User._meta.get_field('email')._unique = True

FUEL_CHOICES = [
        (1, 'Бензин'),
        (2, 'Дизель'),
        (3, 'Газ'),
        (4, 'Газ/Бензин'),
        (5, 'Гибрид'),
        (6, 'Электро'),
        (7, 'Газ метан'),
        (8, 'Газ пропан-бутан'),
        (9, 'Другое')
    ]

DRIVE_SYSTEM_CHOICES = [
        (1, 'Полный'),
        (2, 'Передний'),
        (3, 'Задний')
    ]

TRANSMISSION_CHOICES = [
        (1, 'Ручная/Механика'),
        (2, 'Автомат'),
        (3, 'Типтроник'),
        (4, 'Робот'),
        (5, 'Вариатор')
    ]

class Car(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True)
    vin = models.CharField(max_length=17, blank=True, null=True, verbose_name='VIN-код')
    producer = models.CharField(max_length=300, verbose_name='Марка')
    model = models.CharField(max_length=300, verbose_name='Модель')
    year = models.IntegerField(verbose_name='Год', validators=[MinValueValidator(1800), MaxValueValidator(datetime.date.today().year)])
    transmission = models.PositiveSmallIntegerField(choices=TRANSMISSION_CHOICES, verbose_name='КПП')
    body = models.ForeignKey('Body', on_delete=models.CASCADE, null=True)
    engine = models.ForeignKey('Engine', on_delete=models.CASCADE, null=True)
    fuel = models.PositiveIntegerField(choices=FUEL_CHOICES, verbose_name='Топливо')
    drive_system = models.PositiveSmallIntegerField(choices=DRIVE_SYSTEM_CHOICES, verbose_name='Тип привода')
    mileage = models.IntegerField(blank=True, null=True, validators=[MinValueValidator(1), MaxValueValidator(10000000)], verbose_name='Пробег')
    price = models.FloatField(blank=True, null=True, verbose_name='Стоимость')
    archive = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.producer + ', ' + self.model

    class Meta:
        verbose_name = 'Автомобиль'
        verbose_name_plural = 'Автомобили'


class Body(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True)
    name = models.CharField(blank=True, max_length=100, verbose_name='Тип кузова')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тип кузова'
        verbose_name_plural = 'Типы кузовов'


class Engine(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True)
    name = models.CharField(blank=True, max_length=500, verbose_name='Тип двигателя')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тип двигателя'
        verbose_name_plural = 'Типы двигателей'


class Insurance(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True)
    type = models.CharField(max_length=255, verbose_name='Тип страховки')
    description = models.CharField(blank=True, max_length=500, verbose_name='Описание')
    policy_number = models.CharField(blank=True, max_length=30, verbose_name='Номер страховки')
    start_date = models.DateField(verbose_name='Дата начала')
    end_date = models.DateField(verbose_name='Дата окончания')
    price = models.FloatField(blank=True, null=True, validators=[MinValueValidator(0), MaxValueValidator(1000000)], verbose_name='Стоимость страховки')
    archive = models.BooleanField(default=False)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)

    def __str__(self):
        return self.type

    class Meta:
        verbose_name = 'Страховка'
        verbose_name_plural = 'Страховки'


class CarIssue(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True)
    date = models.DateField(default=datetime.date.today, blank=True)
    name = models.CharField(max_length=255, verbose_name='Название проблемы')
    description = models.CharField(blank=True, null=True, max_length=1000, verbose_name='Описание')
    close = models.BooleanField(default=False, verbose_name='Состояние')
    archive = models.BooleanField(default=False)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Тип неполадки'
        verbose_name_plural = 'Типы неполадок'


class Improvement(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True)
    date = models.DateField(auto_now=True, blank=True)
    name = models.CharField(max_length=255, verbose_name='Название проблемы')
    description = models.CharField(blank=True, null=True, max_length=1000, verbose_name='Описание')
    close = models.BooleanField(default=False, verbose_name='Состояние')
    price = models.FloatField(blank=True, null=True, validators=[MinValueValidator(0), MaxValueValidator(1000000)], verbose_name='Стоимость')
    archive = models.BooleanField(default=False)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Улучшение'
        verbose_name_plural = 'Улучшения'


class Repair(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True)
    type_of_repair = models.PositiveSmallIntegerField(choices=[
        (1, 'ТО'),
        (2, 'Замена запчастей'),
        (3, 'Кузовные работы')
    ])
    name = models.CharField(max_length=400, verbose_name='Название')
    description = models.CharField(blank=True, null=True, max_length=2000, verbose_name='Описание')
    note = models.CharField(blank=True, null=True, max_length=500, verbose_name='Примечание')
    mileage = models.IntegerField(blank=True, null=True, validators=[MinValueValidator(1), MaxValueValidator(10000000)], verbose_name='Пробег')
    price = models.FloatField(blank=True, null=True, validators=[MinValueValidator(0), MaxValueValidator(1000000)], verbose_name='Стоимость')
    date = models.DateField(blank=True)
    archive = models.BooleanField(default=False)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Ремонт'
        verbose_name_plural = 'Ремонты'


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_data/user_<id>(first_number)/user_id/car_id
    user = User.objects.get(car__id=instance.car_id)
    return os.path.join(settings.MEDIA_ROOT, str(user.id)[0], str(user.id), str(instance.car_id) + '.' + str(filename.split('.')[1]))


class CarPhoto(models.Model):
    id = models.AutoField(auto_created=True, primary_key=True)
    image = models.ImageField(upload_to=user_directory_path, blank=True, null=True, verbose_name='Фото')
    car = models.ForeignKey(Car, on_delete=models.CASCADE)

views/carissue_views.py
import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_list_or_404, redirect, get_object_or_404

from Garage.models import Car, CarIssue
from Garage.forms import AddIssueForm, UpdateIssueForm
from views.views import pagination


@login_required()
def get_carissues(request):
    message = None
    user = request.user
    cars = Car.objects.filter(user_id=user.id, archive=False)
    car_issues = []
    if cars:
        for car in cars:
            if list(CarIssue.objects.filter(car_id=car.id, archive=False)) != []:
                car_issues.append(list(CarIssue.objects.filter(car_id=car.id, archive=False)))
        page_obj = pagination(request, sum(car_issues, []), 10)

        context = {
            'user': user,
            'cars': cars,
            'page_obj': page_obj,
            'message': message
        }
    else:
        message = 'У вас нет добавленных автомобилей'
        context = {
            'message': message
        }
    return render(request, 'Garage/car_issues.html', context)


@login_required()
def get_archived_issues(request):
    message = None
    issues = []
    context = {}
    cars = Car.objects.filter(user_id=request.user.id)
    if cars:
        for car in cars:
            if list(CarIssue.objects.filter(car_id=car.id, archive=True)) != []:
                issues.append(list(CarIssue.objects.filter(car_id=car.id, archive=True)))
        if issues:
            page_obj_issues = pagination(request, sum(issues, []), 10)
            context['page_obj_issues'] = page_obj_issues
        else:
            message = 'У вас нет добавленных поломок в папке архив'
    else:
        message = 'У вас нет добавленных автомобилей'
    context['message'] = message
    return render(request, 'Garage/archived_issues.html', context)


@login_required()
def add_issue(request):
    user = request.user
    cars = get_list_or_404(Car, user_id=user.id, archive=False)
    errors = None
    if request.method == 'POST':
        form_issue = AddIssueForm(request.POST)
        if form_issue.is_valid():
            form_issue.save()
            car_id = form_issue.data['car']
            return redirect(f'/car/{car_id}')
        else:
            errors = form_issue.errors

    form_issue = AddIssueForm()
    context = {
        'user': user,
        'cars': cars,
        'form_issue': form_issue,
        'errors': errors
    }
    return render(request, 'Garage/add_issue.html', context)


@login_required()
def update_issue(request, issue_id=None):
    user = request.user
    issue = get_object_or_404(CarIssue, id=issue_id, archive=False)
    car = get_object_or_404(Car, id=issue.car_id, user_id=user.id, archive=False)
    cars = Car.objects.filter(user_id=user.id, archive=False)
    errors = None
    if request.method == 'POST':
        form_issue = UpdateIssueForm(request.POST, instance=issue)
        try:
            datetime.datetime.strptime(form_issue.data['date'], "%Y-%m-%d").date()
            if form_issue.is_valid():
                form_issue.save()
                car_id = form_issue.data['car']
                return redirect(f'/car/{car_id}')
            else:
                errors = form_issue.errors
        except ValueError:
            errors = 'Дата создания поломки должна содержать день, месяц и год!'
    form_issue = UpdateIssueForm()
    context = {
        'cars': cars,
        'car': car,
        'issue': issue,
        'form_issue': form_issue,
        'errors': errors
    }
    return render(request, 'Garage/update_issue.html', context)


@login_required()
def delete_issue(request, issue_id=None):
    user = request.user
    issue = get_object_or_404(CarIssue, id=issue_id)
    car = get_object_or_404(Car, id=issue.car_id, user_id=user.id, archive=False)
    if request.method == 'POST':
        issue.delete()

        messages.add_message(
                request,
                messages.SUCCESS,
                f'Поломка была успешно удалена!'
            )
        return redirect(f'/car/{car.id}')

    context = {'issue': issue}
    return render(request, 'Garage/delete_issue.html', context)


@login_required()
def archive_issue(request, issue_id):
    user = request.user
    issue = get_object_or_404(CarIssue, id=issue_id, archive=False)
    car = get_object_or_404(Car, id=issue.car_id, user_id=user.id, archive=False)
    if request.method == 'POST':
        issue.archive = True
        issue.save()
        return redirect(f'/car/{car.id}')

    context = {
        'issue': issue
    }
    return render(request, 'Garage/archive_issue.html', context)


@login_required()
def unarchive_issue(request, issue_id=None):
    issue = get_object_or_404(CarIssue, id=issue_id, archive=True)
    if request.method == 'POST':
        issue.archive = False
        issue.save()

        return redirect(f'/car/{issue.car_id}')

    context = {
        'issue': issue
    }
    return render(request, 'Garage/unarchive_issue.html', context)

templates/Garage/about_company.html
<section id="about" class="ls section_padding_top_100 section_padding_bottom_75 columns_margin_bottom_30">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-push-6">
                <div class="embed-responsive embed-responsive-3by2">
                    <a href="https://player.vimeo.com/video/1084537" class="embed-placeholder">
                        <img src="static/images/gallery/11.jpg" alt="">
                    </a>
                </div>
            </div>
            <div class="col-md-6 col-md-pull-6">
                <span class="small-text big highlight">
                </span>
                <h2 class="section_header"> О нашей компании </h2>
                <hr class="divider_60_2 main_bg_color">
                <p> Наша компания готова помочь клиентам отслеживать и оптимизировать расходы связанные с транспортными средствами. </p>
            </div>
        </div>
    </div>
</section>

templates/Garage/add_improvement.html
{% extends 'Garage/index.html' %}
{% load static %}
{% block content %}
    <section class="page_breadcrumbs ds parallax section_padding_top_15 section_padding_bottom_15">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 text-center">
                    <h2>Добавить улучшение</h2>
                    <ol class="breadcrumb greylinks">
                        <li>Опции</li>
                        <li> <a href="{% url "improvements" %}">Улучшения</a> </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="ls section_padding_top_100 section_padding_bottom_100 columns_padding_25">
        <div class="container">
            <div class="row">
                <form class="contact-form" action="{% url 'add_improvement' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                    <div class="col-sm-7 col-md-8 col-lg-9">
                        <p class="contact-form">
                            <input type="text" required="true" size="30" value name="name" class="contact-form-name" placeholder="Название" title="Название">
                            <input type="text" aria-required="true" size="30" value name="description" class="contact-form-description" placeholder="Описание" title="Описание">
                        </p>
                        <p>
                            <input type="float" step="0.01" aria-required="false" size="30" value name="price" class="contact-form-price" placeholder="Стоимость" title="Стоимость">
                                {{ errors.price }}
                            {% if cars %}
                                    <p class="contact-form">
                                        <label for="car">Выбери автомобиль:</label>
                                        <select name="car" id="car_id" value="{{ car.id }}">
                                            {% for car in cars %}
                                                <option value="{{ car.id }}">{{ car.producer }}, {{ car.model }}</option>
                                            {% endfor %}
                                        </select>
                                    </p>
                            {% endif %}
                        </p>
                        <input type="submit" value="Сохранить" class="btn-default">
                        {% if errors %}
                            <a href="{% url 'improvements' %}" class="theme_button color1 min_width_button"> Отмена </a>
                        {% else %}
                            <input class="theme_button color1 min_width_button" type="button" value="Отменить" onclick="goBack()">
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

templates/Garage/add_insurance.html
{% extends 'Garage/index.html' %}
{% load static %}
{% block content %}
    <section class="page_breadcrumbs ds parallax section_padding_top_15 section_padding_bottom_15">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 text-center">
                    <h2>Добавить страховку</h2>
                    <ol class="breadcrumb greylinks">
                        <li>Опции</li>
                        <li> <a href="{% url "insurances" %}">Страховки</a> </li>
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <section class="ls section_padding_top_100 section_padding_bottom_100 columns_padding_25">
        <div class="container">
            <div class="row">
                <form class="contact-form" action="{% url 'add_insurance' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                    <div class="col-sm-7 col-md-8 col-lg-9">
                        <p class="contact-form">
                            <input type="text" required size="30" value="{{ form_insrnc.data.type }}" name="type" class="contact-form-producer" placeholder="Тип страховки">
                            <input type="text" aria-required="true" size="30" value="{{ form_insrnc.data.description }}" name="description" class="contact-form-producer" placeholder="Описание">
                        </p>
                        <p class="contact-form">
                            <input type="text" aria-required="false" size="30" value="{{ form_insrnc.data.policy_number }}" name="policy_number" class="contact-form-year" placeholder="Номер полиса">
                            <input type="date" required size="30" value="{{ form_insrnc.data.start_date }}" name="start_date" class="contact-form-mileage" placeholder="Дата начала">
                            <input type="date" required size="30" value="{{ form_insrnc.data.end_date }}" name="end_date" class="contact-form-mileage" placeholder="Дата окончания">
                                {{ form_insrnc.non_field_errors }}
                        </p>
                        <p>
                            <input type="float" step="0.01" aria-required="false" size="30" value="{{ form_insrnc.data.price }}" name="price" class="contact-form-price" placeholder="Стоимость">
                                {{ errors.price }}
                            {% if cars %}
                                    <p class="contact-form">
                                        <label for="car">Выбери автомобиль который был застрахован:</label>
                                        <select name="car" id="car_id" value="{{ car.id }}">
                                            {% for car in cars %}
                                                <option value="{{ car.id }}">{{ car.producer }}, {{ car.model }}</option>
                                            {% endfor %}
                                        </select>
                            {% endif %}
                        </p>
                        <input type="submit" value="Сохранить" class="btn-default">
                        {% if errors %}
                            <a href="{% url 'insurances' %}" class="theme_button color1 min_width_button"> Отмена </a>
                        {% else %}
                            <input class="theme_button color1 min_width_button" type="button" value="Отменить" onclick="goBack()">
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

templates/Garage/archive_improvement.html
<div class="with_padding with_background rounded bottom_color_border_pop_up">
    <form action="{% url 'archive_improvement' impr_id=improvement.id %}" method="POST">
    {% csrf_token %}
        <h4>Вы уверены что хотите отправить в архив данные?</h4>
        <a href="{% url 'update_improvement' impr_id=improvement.id %}" data-dismiss="modal" class="theme_button color1 min_width_button">Нет</a>
        <input type="submit" action="" class="btn btn-danger" value="Да" />
    </form>
</div>

templates/Garage/archived_repairs.html
{% extends 'Garage/index.html' %}
{% load static %}
{% block content %}
<section class="page_breadcrumbs ds parallax section_padding_top_15 section_padding_bottom_15">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h2>Ремонты</h2>
                <ol class="breadcrumb greylinks">
                    <li>Архив</li>
                    <li>Ремонты</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="ls page_portfolio section_padding_top_100 section_padding_bottom_100">
    <div class="container">
        {% if message %}
            <p>{{ message }}</p>
        {% else %}
            <div class="isotope_container isotope row masonry-layout columns_margin_bottom_20">
            {% if page_obj_repairs.paginator.num_pages %}
                <table>
                    <tr>
                        <th>Тип ремонта</th>
                        <th>Название</th>
                        <th>Описание</th>
                        <th>Заметки</th>
                        <th>Пробег</th>
                        <th>Стоимость</th>
                        <th>Дата</th>
                        <th>Автомобиль</th>
                    </tr>
                        {% for r in page_obj_repairs %}
                            <tr>
                                <td>{{ r.get_type_of_repair_display }} <a data-toggle="modal" data-target="#UnarchiveRepair" href="{% url 'unarchive_repair' repair_id=r.id %}"><span class="glyphicon glyphicon-open small-text alignright"></span></a></td>
                                <td>{{ r.name }}</td>
                                {% if r.description %}<td>{{ r.description }}</td>{% else %}<td></td>{% endif %}
                                {% if r.note %}<td>{{ r.note }}</td>{% else %}<td></td>{% endif %}
                                {% if r.mileage %}<td>{{ r.mileage }}</td>{% else %}<td></td>{% endif %}
                                {% if r.price %}<td>{{ r.price }}</td>{% else %}<td></td>{% endif %}
                                <td>{{ r.date }}</td>
                                <td><a href="{% url 'car_profile' car_id=r.car_id %}">{{ r.car }}</a></td>
                            </tr>
                        {% endfor %}
                </table>
                <!-- PAGINATION BLOCK -->
                    {% include "Garage/pagination.html" with obj=page_obj_repairs  tabnumber='13'%}
                <!-- END PAGINATION -->
            {% endif %}
            </div>
        {% endif %}
        <!-- Popup -->
        <div id ="UnarchiveRepair" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                </div>
            </div>
        </div>
        <!-- End Popup -->
    </div>
</section>
{% endblock %}

templates/Garage/delete_insurance.html
<div class="with_padding with_background rounded bottom_color_border_pop_up">
    <form action="{% url 'delete_insurance' insrnc_id=insurance.id %}" method="POST">
    {% csrf_token %}
        <h4>Вы уверены что хотите удалить данные о страховке?</h4>
        <a href="{% url 'update_insurance' insrnc_id=insurance.id %}" data-dismiss="modal" class="theme_button color1 min_width_button">Нет</a>
        <input class="btn btn-danger" type="submit" value="Да, удалить" onclick="goBack()">
    </form>
</div>

templates/Garage/repairs.html
{% extends 'Garage/index.html' %}
{% load static %}
{% block content %}
<section class="page_breadcrumbs ds parallax section_padding_top_15 section_padding_bottom_15">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h2>Ремонты</h2>
                <ol class="breadcrumb greylinks">
                    <li> <a href="#">
                Опции
            </a> </li>
                    <li class="active"> <a href="{% url "repairs" %}">Ремонты</a> </li>
                </ol>
            </div>
        </div>
    </div>
</section>
<section class="ls page_portfolio section_padding_top_100 section_padding_bottom_100">
    <div class="container">
        {% if message %}
            <p>{{ message }}</p>
            <a class="theme_button color1 min_width_button" href="{% url 'add_car' %}">Добавить автомобиль</a>
        {% else %}
            <a class="theme_button color1 min_width_button" href="{% url 'add_repair' %}">Добавить ремонт</a>
            <div class="isotope_container isotope row masonry-layout columns_margin_bottom_20">
                {% if page_obj_repairs.paginator.num_pages %}
                    <table>
                      <tr>
                          <th>Тип ремонта</th>
                          <th>Название</th>
                          <th>Описание</th>
                          <th>Заметки</th>
                          <th>Пробег</th>
                          <th>Стоимость</th>
                          <th>Дата</th>
                          <th>Автомобиль</th>
                      </tr>
                        {% for r in page_obj_repairs %}
                              <tr>
                                  <td><a href="{%  url 'update_repair' repair_id=r.id %}">{{ r.get_type_of_repair_display }}</a></td>
                                  <td>{{ r.name }}</td>
                                  {% if r.description %}<td>{{ r.description }}</td>{% else %}<td></td>{% endif %}
                                  {% if r.note %}<td>{{ r.note }}</td>{% else %}<td></td>{% endif %}
                                  {% if r.mileage %}<td>{{ r.mileage }}</td>{% else %}<td></td>{% endif %}
                                  {% if r.price %}<td>{{ r.price }}</td>{% else %}<td></td>{% endif %}
                                  <td>{{ r.date}}</td>
                                  <td>{{ r.car }}</td>
                              </tr>
                        {% endfor %}
                    </table>
                    <!-- PAGINATION BLOCK -->
                        {% include "Garage/pagination.html" with obj=page_obj_repairs  tabnumber='7'%}
                    <!-- END PAGINATION -->
                {% else %}
                    <p>У вас нет добавленных ремонтов</p>
                {% endif %}
            </div>
        {% endif %}
    </div>
</section>
{% endblock %}

templates/Garage/unarchive_issue.html
<div class="with_padding with_background rounded bottom_color_border_pop_up">
    <form action="{% url 'unarchive_issue' issue_id=issue.id %}" method="POST">
    {% csrf_token %}
        <h4>Вы уверены что хотите вернуть из архива данные о {{ issue.name }}?</h4>
        <a href="#" data-dismiss="modal" class="theme_button color1 min_width_button">Нет</a>
        <input type="submit" action="" class="btn btn-danger" value="Да" />
    </form>
</div>